### ISSUE TITLE
depence is not available

### ISSUE THREAD

**Issue by datlt4** [amrayn/licensepp#39]
`https://github.com/amraynweb/cryptopp-pem` is not available now!
Are you have any alternative?

**Comment by bar0metr** [comment]
> `https://github.com/amraynweb/cryptopp-pem` is not available now! Are you have any alternative?

I found other repo: https://github.com/noloader/cryptopp-pem

**Comment by datlt4** [comment]
@bar0metr thank you so much, i saved a copy on my PC and I also pushed on github https://github.com/datlt4/licensepp-openssl-crow/tree/main/3rdparty%2Fcryptopp-pem
